spring:
  profiles:
    active: dev
    include: common
  application:
    name: SpringBootExample
  http:
    encoding:
      force: true
      charset: utf-8 #http请求的字符编码
      enabled: true
      force-request: true
      force-response: true
#    multipart:
#      enabled: true
#      resolve-lazily: true
#      max-file-size: 16384MB
#      max-request-size: 16384MB
  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
    #  url: jdbc:mysql://localhost:3306/pdc?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=false
    #  username: cdistc
     # password: cd123321
      type: com.zaxxer.hikari.HikariDataSource
#  redis:
#    pool:
#      max-active: 8
#      max-wait: -1
#      max-idle: 8
#      min-idle: 0
#    timeout: 0