mysql:
  schema: pdc

server:
  port: 18888

spring:
  datasource:
      url: jdbc:mysql://localhost:3306/${mysql.schema}?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=false
      username: cdistc
      password: cd123321
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379

#context:
#  listener:
#    classes: anthony.cd.app.pdc.ApplicationStartup
#
#pdc:
#  user-file-dir: D:/tmpfile
#  udp-port: 18889

